# Generated by Django 5.0.6 on 2024-05-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('strength', models.IntegerField(default=0)),
                ('intelligence', models.IntegerField(default=0)),
                ('mental', models.IntegerField(default=0)),
                ('arms', models.IntegerField(default=0)),
                ('legs', models.IntegerField(default=0)),
                ('stomach', models.IntegerField(default=0)),
                ('back', models.IntegerField(default=0)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(blank=True, choices=[(1, 'Intelligence'), (2, 'Mental'), (3, 'Arms'), (4, 'Legs'), (5, 'Stomach'), (6, 'Back')], null=True)),
                ('intensity', models.IntegerField(blank=True, choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('strength', models.IntegerField(default=0)),
                ('intelligence', models.IntegerField(default=0)),
                ('mental', models.IntegerField(default=0)),
                ('arms', models.IntegerField(default=0)),
                ('legs', models.IntegerField(default=0)),
                ('stomach', models.IntegerField(default=0)),
                ('back', models.IntegerField(default=0)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('difficulty', models.IntegerField(blank=True, choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('exercise_type', models.ManyToManyField(related_name='exercise', to='api.exercisetype')),
            ],
        ),
    ]
