# Generated by Django 4.2.13 on 2024-05-15 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_player_start_date_alter_timeline_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='picture',
        ),
    ]
